### ISSUE TITLE
Outdated trimming in outputs.conf for k8s_container logs

### ISSUE THREAD

**Issue by bsda** [GoogleCloudPlatform/container-engine-customize-fluentd#11]
The default settings in outputs.conf  trims any logs larger than 100KB before sending them to stackdriver.
According to  https://cloud.google.com/logging/quotas?hl=sv that limit has increased to 256KB.

    # This section is exclusive for k8s_container logs. Those come with
    # 'stderr'/'stdout' tags.
    # TODO(instrumentation): Reconsider this workaround later.
    # Trim the entries which exceed slightly less than 100KB, to avoid
    # dropping them. It is a necessity, because Stackdriver only supports
    # entries that are up to 100KB in size.
    <filter {stderr,stdout}>
      @type record_transformer
      enable_ruby true
      <record>
        message ${record['message'].length > 100000 ? "[Trimmed]#{record['message'][0..100000]}..." : record['message']}
      </record>
    </filter>

This issue is also present in GKE but I'm not sure who to report it to, any chance you guys can pass it along?

Thanks

**Comment by jpatokal** [comment]
Merged, thanks for the fix!
