### ISSUE TITLE
Update DaemonSet Example for Kube 1.16

### ISSUE THREAD

**Issue by rebeccatang16** [GoogleCloudPlatform/container-engine-customize-fluentd#13]
Since daemonsets in `extensions/v1beta1` are being [removed](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/), could [this example](https://github.com/GoogleCloudPlatform/kubernetes-engine-customize-fluentd/blob/master/kubernetes/fluentd-daemonset.yaml) be updated to apps/v1, for compatibility with GKE 1.16?

Thanks

**Comment by jpatokal** [comment]
Thanks for flagging, this has already been fixed in commit https://github.com/GoogleCloudPlatform/kubernetes-engine-customize-fluentd/commit/ad103cd90b5f88181ab4b197927434c482717b10.
