### ISSUE TITLE
Unable to export to Monitoring service

### ISSUE THREAD

**Issue by jbrilla** [GoogleCloudPlatform/container-engine-customize-fluentd#18]
Working on upgrading the images for the custom gke logging agent we have set up.

We're moving from:
gcr.io/stackdriver-agents/stackdriver-logging-agent:1.6.17-16060
k8s.gcr.io/prometheus-to-sd:v0.5.2
TO
gcr.io/stackdriver-agents/stackdriver-logging-agent:1.8.4
gke.gcr.io/prometheus-to-sd:v0.10.0-gke.0

I see logs are coming through to stackdriver but I'm trying to troubleshoot this issue and wondering if it is anything to worry about or if it can be fixed. Thanks

ERROR:`
fluentd-app-logs-tw58b fluentd-app-logs Unable to export to Monitoring service because: GaxError RPC failed, caused by 3:One or more TimeSeries could not be written: The set of resource labels is incomplete. Missing labels: (container_name namespace_id pod_id).: timeSeries[0]. debug_error_string:{"created":"@1609356738.405446538","description":"Error received from peer ipv4:172.217.8.10:443","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"One or more TimeSeries could not be written: The set of resource labels is incomplete. Missing labels: (container_name namespace_id pod_id).: timeSeries[0]","grpc_status":3}`

**Comment by igorpeshansky** [comment]
What container is issuing this error?

**Comment by jbrilla** [comment]
from the fluentd container. the prometheus logs look fine

**Comment by igorpeshansky** [comment]
Ah, I think I see what's going on. You must be seeing the effect of the default agent config in the logging agent container. The default value of `monitoring_type` was switched from `prometheus` to `opencensus` in [1.6.25](https://github.com/GoogleCloudPlatform/google-fluentd/releases/tag/1.6.25), so the agent is attempting to write directly to the API.

You should be able to fix this as follows:
- in `fluentd-configmap.yaml`:
  - split out `output.conf` into its own configmap, named, e.g., `fluentd-gcp-main-config`
  - rename `output.conf` to `google-fluentd.conf`
  - add `@include config.d/*.conf` as the first line of that file
- in `fluentd-daemonset.yaml`:
  - add a `configmap` object for `fluentd-gcp-main-config`, named, e.g., `default-config-volume`:
    ```
      - configMap:
          defaultMode: 420
          name: fluentd-gcp-main-config
        name: default-config-volume
    ```
  - add a mount of the `google-fluentd.conf` subpath of `default-config-volume` onto `/etc/google-fluentd/google-fluentd.conf`, e.g.:
     ```
              - mountPath: /etc/google-fluentd/google-fluentd.conf
                subPath: google-fluentd.conf
                name: default-config-volume
     ```
The above should override the default agent config from the container image and fix the issue for you.

**Comment by jbrilla** [comment]
thanks @igorpeshansky - I think it worked. Let me do some more testing tomorrow when I have more time.

**Comment by jbrilla** [comment]
This is working now. No more errors. Thanks

**Comment by jpatokal** [comment]
Reopening this so I can check @igorpeshansky 's suggested changes into master.

**Comment by jpatokal** [comment]
Merge completed.
